### ISSUE TITLE
So your wifi psk is this huh?

### ISSUE THREAD

**Issue by rahatzamancse** [addy-dclxvi/void-bspwm-dotfiles#5]
Thanks for let us enjoy free wifi around you ;)

Hacked it lol.

https://github.com/addy-dclxvi/void-bspwm-dotfiles/blob/2e783c05073e2dcb2c952c9eeada0519c410528a/etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf#L3

**Comment by addy-dclxvi** [comment]
Of course that's not my real WPA2/PSK key 😅

**Comment by rahatzamancse** [comment]
Then whats the point of keeping it?

**Comment by addy-dclxvi** [comment]
Just for example 😅
